### ISSUE TITLE
Add /submit-joke command

### ISSUE THREAD

**Issue by pitzzahh** [pitzzahh/pitzzahh-bot#62]
### Reason
Provide a way for users to send their own jokes
___
### Tasks
- [ ] Add category, language and the joke as options (**required**)
- [ ] Make language optional (**Use algorithms or Artificial Intelligence to check what language the joke is**)
- [ ] Send a response back to the user
- [ ] Approve jokes that was sent (**Can be done by the owner or with the respected role**)

**Comment by pitzzahh** [comment]
### Additional Task
- [ ] Exclude text channels where the command is available
