### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pitzzahh** [pitzzahh/pitzzahh-bot#67]
### Tasks
- [ ] Add information about the chat commands
- [ ] Add information about the slash commands
- [ ] Add information about some moderation
- [ ] Add information about admin/certain elevated role functionalities
